### ISSUE TITLE
Results for ”Start typing an address” not accurate

### ISSUE THREAD

**Issue by choirboy07** [ServiceInnovationLab/FSD#121] opened 2019-02-11 22:54 UTC
Examples:
New Plymouth Budget Service located at 32 Leach Street New Plymouth.

Search 1 (distance 25km).

Search by entering (and selecting) 36 Leach Street New Plymouth

Expected result: New Plymouth Budget Service showing at top

Results: 1 result = Whanau Pakari with address as 118 Tukapa Street New Plymouth.

Search 2 (distance 25km).

Select Category = Budgeting/Financial Capability and enter (select) 36 Leach Street New Plymouth

Expected result: New Plymouth Budget Service showing at top

Results: 1 result = New Plymouth Budget Advisory Service

General issue

Search 3 (distance 100km).
Select Category = Child Care
Search by entering (and selecting) 56 the Terrace Wellington Central

Expected result: 115 results

Results: 4 results only

Search 4 (distance 100km) 
Select Category = Child Care
Search by entering (and selecting) Wellington Central

Expected result: 115 results

Results:  8 results only (no Lower Hutt based providers but 1 Upper Hutt based)

Search 5
Select Category = Child Care
Search by entering (and selecting) Lower Hutt

Expected result: 26 results

Results:  9 results only (no Lower Hutt based providers)
Note there are 26 “Local” providers under Child Care for Lower Hutt on the Family Services Directory (FSD).  The first result on the FSD is showing on Searchinator for a topic search (searched for Greenstone).  Checked the data.govt extract and it is in the Extract with Child Care as a Level 1.

**Comment by lamorrison** [comment] 2019-02-13 02:52
This is caused by the implementation of distance filtering as a client-side operation. 

An initial set of results is retrieved from the server without considering the location, then the results are filtered based on distance to the provided location.

If no other search criteria are provided the results will be the top 100 (result batch limit) results from the database without any refinement, then sort and filter those by distance, but there are likely to be relevant results which aren't in that arbitrary list of 100 in the first place.

**Comment by lamorrison** [comment] 2019-02-13 02:57
I've directed a query to Cam about options for doing geolocation search on the server. I believe it's a Postgres database and we probably have access to a full query language (based on reading https://docs.ckan.org/en/2.8/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search).

If we can't do a query to order by distance in the database, there are a few other options to improve the results
- Add the location as an invisible search term (depends on the street address being part of the searched text)
- Do some string comparison between the search location and the result locations (e.g. if the first n characters of the latitude and longitude match, the location is definitely close to the search location)

**Comment by lamorrison** [comment] 2019-02-14 04:25
Progress update: I've found that adding the address (and category) as invisible search terms if there are no keywords is a simple and effective workaround. I need to test it a bit more before closing this ticket.

**Comment by choirboy07** [comment] 2019-02-14 05:15
Solid effort. Thanks.

Paul.
________________________________

**Comment by lamorrison** [comment] 2019-02-18 20:21
I've found an underlying issue for this story and #47 which is that CKAN is returning search results lowest-score-first, will talk to Cam about how to reverse that. It causes a problem for vague searches, but more specific searches will have a small number of relevant results so the best results will still be visible.

A query for reference:
https://catalogue.data.govt.nz/api/3/action/datastore_search?resource_id=35de6bf8-b254-4025-89f5-da9eb6adf9a0&fields=FSD_ID,PROVIDER_CLASSIFICATION,LONGITUDE,LATITUDE,PROVIDER_NAME,PUBLISHED_CONTACT_EMAIL_1,PUBLISHED_PHONE_1,PROVIDER_CONTACT_AVAILABILITY,ORGANISATION_PURPOSE,PHYSICAL_ADDRESS,PROVIDER_WEBSITE_1&q=budget new plymouth&limit=36

**Comment by lamorrison** [comment] 2019-02-19 04:48
I've found a workaround for ^ that issue, which is in code review now.

**Closed** 2019-02-19 21:34 UTC
Labels: bug, review
