### ISSUE TITLE
Show number of results

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/FSD#191] opened 2019-03-17 21:29 UTC
As a user, I want to be able to see next to the search results the number of results it's been returned, so I can check against the other search engine.

A / C
 - Searching for: <<name>> near <<address>> Results <<number>>

**Comment by JacOng17** [comment] 2019-03-18 00:10
Duplicate of #196

**Closed** 2019-03-18 00:09 UTC
Labels: to do
