### ISSUE TITLE
Number results

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/FSD#198] opened 2019-03-17 22:42 UTC

**Comment by lamorrison** [comment] 2019-03-17 22:46
Number the search results so they are easier to refer to in conversation

Acceptance Criteria
- [ ] Each search result has a visible result number

**Comment by JacOng17** [comment] 2019-03-25 00:18
DONE, but not merged. A feature we can turn on when needed.
![Numbering of results.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bbfc42dd4762b0011a329b7/125516c66e82c728ace21e0d46c68197218791a081eeff4ca21de2913a532b673a46ef696097ec22ba416f43554d4bff40505c16f4aadf78a3b434268a5c0dbf826d567c943c03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28e8c4b391d041980f8583db2d4.png)

**Comment by JacOng17** [comment] 2019-03-27 21:28
There's nothing to be tested for this. Just able to see on the dev environment

**Comment by JacOng17** [comment] 2019-03-27 21:42
Duplicate of #229

**Closed** 2019-03-27 21:43 UTC
Labels: review
